name: Build & Push

on:
  workflow_call:
    inputs:   
      dockerfile:
        required: false
        type: string  
        default: "deploy/docker/Dockerfile" 
      image:
        required: true
        type: string
        default: ""

  
jobs: 
  build:
   runs-on: ubuntu-22.04
   steps:
    - name: Check out code
      uses: actions/checkout@v3
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
        aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        aws-region: ${{secrets.AWS_REGION}}
    
    - name: Login to ecr
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - uses: jwalton/gh-find-current-pr@v1
      id: findPr
      with:
        state: open

    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2.3.1
      with:
        key: ${{ secrets.SSH_KEY }} 
        known_hosts: echo $(ssh-keyscan -t rsa github.com)
    
    - name: Copy SSH Key
      shell: bash
      run: cp ~/.ssh/id_rsa .

    - name: Build, tag and push pr image to ecr
      if: github.ref != 'refs/heads/main' && steps.findPr.outputs.number
      uses: appleboy/docker-ecr-action@master
      with:
        access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
        secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        registry: ${{steps.login-ecr.outputs.registry}}
        repo: ${{ inputs.image }}
        region: ${{secrets.AWS_REGION}}
        tags: pr-${{steps.findPr.outputs.pr}}-${{github.run_number}}
        dockerfile: ${{ inputs.dockerfile }}
        context: .

    - name: Build, tag, and push image to ecr
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: appleboy/docker-ecr-action@master
      with:
        access_key: ${{secrets.AWS_ACCESS_KEY_ID}}
        secret_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        registry: ${{steps.login-ecr.outputs.registry}}
        repo: ${{ inputs.image }}
        region: ${{secrets.AWS_REGION}}
        tags: ${{github.run_number}}
        dockerfile: ${{ inputs.dockerfile }}
        context: .