name: GO-CI

# Controls when the workflow will run
on:    
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string
        default: "1.19"
    

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out code
        uses: actions/checkout@v3

      - name: Git config setup to use ssh instead of http
        run: git config --global url."git@github.com:".insteadOf https://github.com/
      
      - name: Setting private repos for golang
        run: export GOPRIVATE=github.com/iot-universe

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.SSH_KEY }} 
          known_hosts: echo $(ssh-keyscan -t rsa github.com)

      - name: Copy SSH Key
        shell: bash
        run: cp ~/.ssh/id_rsa .
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ inputs.go-version }}
      
      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...