name: Go-Security-CI

on: 
  workflow_call:
    inputs:
      go-version:
        required: true
        type: string
        default: "1.19"

jobs: 
  security:
    runs-on: ubuntu-22.04
    env:
      GO111MODULE: on
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Git config setup to use ssh instead of http
        run: git config --global url."git@github.com:".insteadOf https://github.com/
      
      - name: Setting private repos for golang
        run: export GOPRIVATE=github.com/iot-universe
      
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.SSH_KEY }} 
          known_hosts: echo $(ssh-keyscan -t rsa github.com)

      - name: Copy SSH Key
        shell: bash
        run: cp ~/.ssh/id_rsa .

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{inputs.go-version}}

      # - name: Install go sec
      #   uses: go install github.com/securego/gosec/v2/cmd/gosec@latest
      
      # - name: run go sec
      #   run: GO111MODULE=on gosec ./...


      # - name: run go sec
      #   uses: ynniss/golang-security-action@master
      #   with: 
      #     CODE_PATH: "./..."


      # - name: Build
      #   run: go build -v ./...
        
      # - name: Run Gosec Security Scanner
      #   uses: securego/gosec@master
      #   with:
      #     args: ./...

      - name: Run Gosec Security Scanner
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          go get github.com/securego/gosec/cmd/gosec
          gosec ./...