name: Go-Security-CI

on: 
  workflow_call:

jobs: 
  security:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Setting private repos for golang
        run: export GOPRIVATE=github.com/iot-universe
      
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: ${{ secrets.SSH_KEY }} 
          known_hosts: echo $(ssh-keyscan -t rsa github.com)

      - name: Copy SSH Key
        shell: bash
        run: cp ~/.ssh/id_rsa .

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Install go sec
        uses: securego/gosec@master
        run: GO111MODULE=on gosec ./...